#!/bin/sh

set -e

rm -rf 'DispatchOvercommitTest' 'DispatchOvercommitTest.dSYM'

clang-format -i 'Entry Point.c'

clang \
	-fmodules \
	-g \
	-W \
	-Wall \
	-Wextra \
	-Wpedantic \
	-Wconversion \
	-Wimplicit-fallthrough \
	-Wmissing-prototypes \
	-Wshadow \
	-Wstrict-prototypes \
	-o 'DispatchOvercommitTest' \
	'Entry Point.c'
